### ISSUE TITLE
Automatic attribution for copied code

### ISSUE THREAD

**Issue by amitness** [studenton/cutcode#10]
See if it's possible to implement a feature such that:

- Code copied from Stackoverflow has a automatic attribution similar to:
    ```javascript
    /*  
   Reference: https://www.stackoverflow.com/...
    */
    ```
- This setting should be turned off by default and can be enabled from the settings page of extension.

**Issues**:
- Comment style depends on the programming language
- How to determine the programming language of the copied code?
- Does the implementation bring added complexity to the extension?

**Comment by willbiddy** [comment]
One thing that could be done is find the language from the tags from the original question. For example, this question ([https://stackoverflow.com/questions/89228/calling-an-external-command-in-python](https://stackoverflow.com/questions/89228/calling-an-external-command-in-python)) is tagged with "python", so any code posted is probably python code.

**Comment by studenton** [comment]
I'll currently busy with exams so will look into it in a few days. If you wanna try it in the mean time, you're free to.
