### ISSUE TITLE
Put extension on chrome web store or firefox

### ISSUE THREAD

**Issue by willbiddy** [studenton/cutcode#11]
This would be a lot easier for people to install if they didn't have to clone the git repository and load the unpacked extension. Putting it on the chrome web store (and Firefox if we wan't to do that to) would be a good idea.

Here's some more information about doing that:
[https://developer.chrome.com/webstore/publish](https://developer.chrome.com/webstore/publish
)
[https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension)

**Comment by hereabdulla** [comment]
Still it is not published in Firefox addons, @amitness shall you publish the same ASAP

**Comment by amitness** [comment]
@hereabdulla Doing it now. Thanks for the interest :smile:

**Comment by amitness** [comment]
Awaiting approval from Mozilla now.

**Comment by amitness** [comment]
@hereabdulla And here it comes: https://addons.mozilla.org/en-US/firefox/addon/cutcode/ . Please try it out.
