### ISSUE TITLE
Add more sites where extension is enabled

### ISSUE THREAD

**Issue by amitness** [studenton/cutcode#25]
Some sites:

https://askubuntu.com
https://*.stackexchange.com/

**Comment by kot91** [comment]
Make it user specified in the options with the few that are listed as defaults.

**Comment by amitness** [comment]
@kot91 I like the idea. Please create a new issue for that.

**Comment by Paarmita** [comment]
If wanted to make as default we could add all the code sites like geeks for geeks and others also

**Comment by amitness** [comment]
@Paarmita Thank you for the suggestion. I'll add it when I work on this issue.
