### ISSUE TITLE
User defined websites the extension works with

### ISSUE THREAD

**Issue by Ethicmeta** [studenton/cutcode#32]
In user settings, allow them to select which websites they want the extension to work with, with a default list that are currently in use.

**Comment by amitness** [comment]
Sounds good.

**Comment by kot91** [comment]
@amitness I will not be working on this or any other issues on this repository due to work related projects on my plate. Good luck with the project :)

**Comment by miguelgrc** [comment]
As my PR, I made an attempt at implementing this in #33

The list defaults to just StackOverflow, and can be filled with a comma-separated sequence of websites. Writing just a single dot allows the extension to work everywhere.
