### ISSUE TITLE
Extension works in Firefox

### ISSUE THREAD

**Issue by willbiddy** [studenton/cutcode#4]
I've tested the extension in Firefox and it works without changing any of the code! I think we should start editing the readme to say that it works in Firefox and add some instructions about how to install it there.

**Comment by studenton** [comment]
Cool @willbiddy . Would you like to pick up and work on this?

**Comment by studenton** [comment]
Thanks @willbiddy for the guide.

**Comment by kot91** [comment]
What did you load for Firefox? I'm getting various errors when trying to load it;

- selecting inject.js results in "cutcode\scripts\stackoverflow does not contain a valid install manifest" moving the manifest into the same dir doesnt change anything either. 

- all other files result in Extension is invalid

totally new to this, by the way. I found your post on yourfirstpr.github.io

**Comment by studenton** [comment]
@willbiddy Please help @kot91 .

**Comment by willbiddy** [comment]
I went to the cutcode directory and chose `manifest.json`. Try that and see if it works. @kot91

**Comment by kot91** [comment]
@willbiddy 
> There was an error during installation: Extension is invalid

I am using Firefox version 52.0 32-bit btw :)

**Comment by willbiddy** [comment]
I don't really know how to debug it because it works fine for me. Someone might want to look through some of [these search results](https://www.google.com/search?q=There+was+an+error+during+installation%3A+Extension+is+invalid) and see if any of them have solutions.

**Comment by kot91** [comment]
@willbiddy What firefox version are you using? I dumbed down the manifest to the three required keys and it throws correct errors with mistakes (like a left over comma) but the second I have a correctly formatted manifest it throws that generic error.

**Comment by kot91** [comment]
update: @willbiddy @studenton 

the issue was manifest_version cannot be greater than 2 in firefox. I figured this out using the web-ext run --verbose option. it loads properly now :)

**Comment by studenton** [comment]
@kot91 Will made the change to the manifest. Can you test it and confirm? Then I'll close the issue.

**Comment by kot91** [comment]
go ahead and close this :)
