### ISSUE TITLE
Automatically remove >>> from code

### ISSUE THREAD

**Issue by amitness** [studenton/cutcode#8]
In Stackoverflow, some code snippets have a preceeding `>>>` to show that it's running on interpreter or shell.

For example:

```shell
>>> names = ['King', 'Queen', 'Joker']
>>> any(n in 'King and john' for n in names)
True
```

A feature to remove those symbols from the code when it's copied to clipboard will be useful.

**Comment by AbsoluteZero273** [comment]
Can you share the link of SO post where such is written?

**Comment by studenton** [comment]
@AbsoluteZero273 I found one here: http://stackoverflow.com/questions/13650293/understanding-pythons-is-operator

**Comment by AbsoluteZero273** [comment]
What about the output in the shell like `True` in above example? Do we remove them?

**Comment by studenton** [comment]
If possible, yes.

**Comment by amitness** [comment]
@AbsoluteZero273 This has some edge cases where it doesn't work, so closing it. Thanks for the work :+1:
