### ISSUE TITLE
Implement a settings page for the extension

### ISSUE THREAD

**Issue by amitness** [studenton/cutcode#9]
Implement a settings page to allow user to turn on / off any new features. 

- Use minimal design

**Comment by kot91** [comment]
to add to this;

- ability to change the event that triggers the copy

**Comment by kot91** [comment]
@studenton I will start working on this today :)

**Comment by kot91** [comment]
The settings page is pretty straight forward and depends entirely on what we want to let users define. What features do you think we should allow users to define? The only thing I have come up with so far is ability to change event listener from double click to whatever the user wants. @studenton @willbiddy

**Comment by willbiddy** [comment]
- Turning on or off whether they want a comment with the attribution. Although we don't have that set up yet.
- Maybe let them change some of the styling, like the color of the box when something's copied.
- A link to the GitHub repo somewhere sounds like a good idea too

**Comment by kot91** [comment]
@willbiddy the homepage_url in the manifest displays in the settings page by default :) 

I'll try integrating a checkbox for my iteration of attribution (which should be fairly easily adapted to whatever fork is chosen if we use a string concatenation to include attribution).

Color should be easy as well :)

**Comment by kot91** [comment]
my PR addresses this feature request :)
